### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [antonMihalev/site-j-wood#1]
- Иконки соц сетей странно сплющило
- Проверь свой css `padding: 00px;`
- Очень плохо обращаться ко всему, особенно для задания шрифта 
```
* {
    padding: 00px;
    margin: 0px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}
```
- шрифты с тенюшками уже не в моде
- зелень в цвете не читается на Главном Экране
- сделай красиво для 1200px, я со своим экранчиком страдаю(

**Comment by antonMihalev** [comment]
Спасибо за issue, вроде бы все исправил. Чекни плиз
