### ISSUE TITLE
Баги 2.0

### ISSUE THREAD

**Issue by yuchiko** [antonMihalev/site-j-wood#3]
**HTML**
- тут странный дубляж
`<div class="nav__nav_item">` -> `<div class="nav_item">`
- id это уже уникальное название, а то с привязкой к контейнеру, мне не нравится, не уверен, что id тут вообще надо
`<div class="about__container" id="about__container">`
- Название варианта контактов вообще не заголовок
```
<h2>mail:</h2>
<h2>phone:</h2>
```
- Иногда ты используешь в классах `__`, а иногда `_` постарайся выбрать что-то одно

**CSS**
- Ты мог не делать второе медиа, а просто указать, что-то по дефолту для `.menu_line`
```
.menu_line {
  margin: 0px auto 15px;
  width: 90%;
  height: 1px;
  background-color: grey; }
  @media (min-width: 668px) {
    .menu_line {
      display: none; } }

@media (max-width: 668px) {
  .menu_line {
    display: block; } }
```
- Ты всюду дублируешь это правило, почему его не обьединить под одним классом ?
`max-width: 1920px;`

**Comment by antonMihalev** [comment]
Спасибо,все пофиксил)
